/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homeintrusion;
import java.awt.BorderLayout;
import java.io.*;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
public class EntryScreen extends javax.swing.JFrame {
String entryN = "";
ArrayList<String> allPasswords = new ArrayList<String>();
 ArrayList<String> entries = new ArrayList<String>();
 ArrayList<String> passwordsPerEntry = new ArrayList<String>();
    public EntryScreen() {
        initComponents();
    }
    
    public EntryScreen(String entryName) {
        entryN = entryName;
        initComponents();
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pWord = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        entry = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Enter Password");

        jButton1.setText("show password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        entry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRY1", "ENTRY2", "ENTRY3" }));

        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("display speeds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("display trials");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pWord, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton4)))))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(entry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
       FileInputStream fis = new FileInputStream("obj.ser");
       ObjectInputStream ois = new ObjectInputStream(fis);
       
       allPasswords.clear();
       allPasswords = (ArrayList<String>) ois.readObject();
       
       String allPwords = "";
       for(int i=0;i<allPasswords.size();i++){
           allPwords += allPasswords.get(i)+"\r\n";
       }
       
       FileOutputStream fos = new FileOutputStream("pwords.txt");
       fos.write(allPwords.getBytes());
       fos.close();
       
       Runtime r = Runtime.getRuntime();
       r.exec("notepad pwords.txt");
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        entries.clear();
        entries.add("ENTRY1");
        entries.add("ENTRY2");
        entries.add("ENTRY3");
        String selEntry = entry.getSelectedItem().toString();        
        int index = entries.indexOf(selEntry);
        String password = allPasswords.get(index);
        String pwd = pWord.getText();
        if(pwd.equals(password)){
            
            JOptionPane.showMessageDialog(null, "success");       
            
            DashBoardFinal db = new DashBoardFinal(selEntry);
            db.setSize(750,750);
            db.setVisible(true);
            //new DashBoard(selEntry).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "sorry"); 
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
        
        passwordsPerEntry.clear();
        char[] CHARSET_AZ_09 = "ABCDEFGHIJKLMNOPQRSVZ0123456789".toCharArray();
        String firstEntry=Otp.randomString(CHARSET_AZ_09, 6);
        String secondEntry=Otp.randomString(CHARSET_AZ_09, 6);
        String thirdEntry=Otp.randomString(CHARSET_AZ_09, 6);
        
        passwordsPerEntry.add(firstEntry);
        passwordsPerEntry.add(secondEntry);
        passwordsPerEntry.add(thirdEntry);
        
        FileOutputStream fos = new FileOutputStream("obj.ser");
        ObjectOutputStream os = new ObjectOutputStream(fos);
        os.writeObject(passwordsPerEntry);
        os.close();
        fos.close();
        
        
        System.out.println(passwordsPerEntry);
        
        
//           HomeDeployment hd = new HomeDeployment();
//           hd.setVisible(true);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DisplaySpeeds ds = new DisplaySpeeds();
      ds.displaySpeeds();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
        String firstPath = "trials/home1/trial.txt";
        String secondPath = "trials/home2/trial.txt";
        String thirdPath = "trials/home3/trial.txt";
        String fourthPath = "trials/home4/trial.txt";
        String fifthPath = "trials/home5/trial.txt";
        ArrayList<String> homeNames = new ArrayList<String>();
        homeNames.clear();
        homeNames.add("home1");
        homeNames.add("home2");
        homeNames.add("home3");
        homeNames.add("home4");
        homeNames.add("home5");
        ArrayList<String> trials = new ArrayList<String>();
        trials.clear();
        ReadFileData rd = new ReadFileData();
        trials.add(rd.fileData(firstPath));
        trials.add(rd.fileData(secondPath));
        trials.add(rd.fileData(thirdPath));
        trials.add(rd.fileData(fourthPath));
        trials.add(rd.fileData(fifthPath));
        //
         JFrame frame = new JFrame();
            Vector<Vector> rowData = new Vector<Vector>();
            rowData.clear();
            Vector<String> row = null;
            Vector<String> columnNames = new Vector<String>();
            columnNames.clear();
            columnNames.addElement("HOME NAME");
            columnNames.addElement("TRIALS COUNT");
            for (int i = 0; i < homeNames.size(); i++) {
                row = new Vector<String>();
                row.add(homeNames.get(i));
                row.add(trials.get(i).toString());
                rowData.add(row);
            }
            JTable table = new JTable(rowData, columnNames);
        JTableHeader header = table.getTableHeader();
        header.setDefaultRenderer(new KeepSortIconHeaderRenderer(header.getDefaultRenderer()));
        table.getTableHeader().setDefaultRenderer(new HeaderRenderer());

        JScrollPane scrollPane = new JScrollPane(table);

        frame.add(scrollPane, BorderLayout.CENTER);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 200);
        frame.setTitle("HOME TRIALS");
        frame.setVisible(true);
        frame.setResizable(true);
        //
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> entry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pWord;
    // End of variables declaration//GEN-END:variables
}
